name: Deploy to Github Pages
permissions:
  contents: write
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: Publish .NET Core Project
        run: dotnet publish rcsign.github.io.csproj -c Release -o release --nologo
      - name: Change index.html root tag
        run: sed -i 's/<base href="\/" \/>/<base href="\/rcsign.github.io\/" \/>/g' release/wwwroot/index.html
      - name: Commit wwwroot to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
